In [1]:
import pandas as pd
from pandasql import sqldf
import seaborn as sns
import matplotlib.pyplot as plt

C:\Users\Jhirs\AppData\Local\Temp\ipykernel_14864\3371965745.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
income = pd.read_csv("https://raw.githubusercontent.com/fundamentals-of-data-science/datasets/master/income.csv")

In [3]:
from pandas.core.algorithms import value_counts
from pandas.core.reshape.concat import concat
import warnings

warnings.filterwarnings('ignore')

In [4]:
def summarize_category(series):
    res_regu = value_counts(series)
    res_norm = value_counts(series, normalize=True)
    result = concat([res_regu, res_norm], axis=1, keys=['Count', 'Frequency'])
    result = result.sort_index()
    return result

def conditional_probability(df, target, givens, cell="index"):
    """
    calculates a simple conditional probability (only one target variable) based off of:
    https://stackoverflow.com/questions/54040923/change-order-of-pandas-multiindex
    
    P(target|givens...)
    
    df: the DataFrame to use for the calculation
    target: the string name of the target variable
    givens: a string or List of strings that represent the "givens"
    cell: a column that is neither target nor givens to "count". Should be a column without NA.
    
    The default assumes you have added a column: df["index"] = df.index to your DataFrame.
    """
    if isinstance(givens, str):
        givens = [givens]
    print(f"P({target}|{', '.join(givens)})")
    columns = [target] + givens
    # handling multiple targets would require a more sophisticated join.
    result = (df.groupby(columns).count() / df.groupby(givens).count())[cell]
    # this makes sure the target is always the column
    result = result.reorder_levels(givens + [target]).sort_index()
    # this flattens the hiearchical index and should fill in missing values.
    result = result.unstack(fill_value=0.0)
    return pd.DataFrame(result)

In [6]:
income['decade'] = (income['age'] // 10) * 10

OptionError: Pattern matched multiple keys

In [7]:
agi_ = conditional_probability(income, 'agi', ['decade', 'sex', 'race', 'occupation', 'education_years'], 'class')
agi_

P(agi|decade, sex, race, occupation, education_years)

agi                                                                <=50K  >50K
decade sex    race               occupation       education_years
10     Female Amer-Indian-Eskimo ?                10                 1.0   0.0
                                 Adm-clerical     6                  1.0   0.0
                                                  7                  1.0   0.0
                                 Other-service    6                  1.0   0.0
                                                  7                  1.0   0.0
...                                                                  ...   ...
90     Male   White              Prof-specialty   13                 1.0   0.0
                                                  15                 0.0   1.0
                                 Protective-serv  4                  1.0   0.0
                                 Sales            13                 0.5   0.5
                                 Transport-moving 9                  1.0   0.0

[3368 rows x 2 columns]

In [1]:
dict = {
    "orders": [
        {
            "items": [
                {
                    "name": "coffee",
                    "price": 2.75
                }
            ],
            "charges": {
                "date": "04/01/21 11:16",
                "subtotal": 2.75,
                "taxes": 0.19,
                "total": 2.94
            }
        }
    ]
}

In [6]:
print(dict['orders'][0]['items'][0]['name'])

coffee

In [12]:
agi_.head(50)

agi                                                                 <=50K  \
decade sex    race               occupation        education_years
10     Female Amer-Indian-Eskimo ?                 10                 1.0
                                 Adm-clerical      6                  1.0
                                                   7                  1.0
                                 Other-service     6                  1.0
                                                   7                  1.0
                                 Sales             7                  1.0
                                                   9                  1.0
                                                   10                 1.0
              Asian-Pac-Islander ?                 7                  1.0
                                                   8                  1.0
                                                   9                  1.0
                                                   10                 1.0
                                 Adm-clerical      7                  1.0
                                                   9                  1.0
                                 Other-service     4                  1.0
                                                   9                  1.0
                                                   10                 1.0
                                 Prof-specialty    8                  1.0
                                 Sales             7                  1.0
                                                   9                  1.0
                                                   10                 1.0
              Black              ?                 6                  1.0
                                                   7                  1.0
                                                   9                  1.0
                                                   10                 1.0
                                                   13                 1.0
                                 Adm-clerical      7                  1.0
                                                   9                  1.0
                                                   10                 1.0
                                                   11                 1.0
                                 Craft-repair      9                  1.0
                                 Handlers-cleaners 7                  1.0
                                                   8                  1.0
                                                   10                 1.0
                                 Machine-op-inspct 9                  1.0
                                 Other-service     5                  1.0
                                                   6                  1.0
                                                   7                  1.0
                                                   9                  1.0
                                                   10                 1.0
                                 Priv-house-serv   6                  1.0
                                 Sales             6                  1.0
                                                   7                  1.0
                                                   8                  1.0
                                                   9                  1.0
                                                   10                 1.0
              Other              ?                 6                  1.0
                                                   7                  1.0
                                                   8                  1.0
                                                   9                  1.0

agi                                                                 >50K
decade sex    race               occupation        education_years
10     Female Amer-Indian-Eskimo ?                 10                0.0
                                 Adm-clerical      6                 0.0
                                                   7                 0.0
                                 Other-service     6                 0.0
                                                   7                 0.0
                                 Sales             7                 0.0
                                                   9                 0.0
                                                   10                0.0
              Asian-Pac-Islander ?                 7                 0.0
                                                   8                 0.0
                                                   9                 0.0
                                                   10                0.0
                                 Adm-clerical      7                 0.0
                                                   9                 0.0
                                 Other-service     4                 0.0
                                                   9                 0.0
                                                   10                0.0
                                 Prof-specialty    8                 0.0
                                 Sales             7                 0.0
                                                   9                 0.0
                                                   10                0.0
              Black              ?                 6                 0.0
                                                   7                 0.0
                                                   9                 0.0
                                                   10                0.0
                                                   13                0.0
                                 Adm-clerical      7                 0.0
                                                   9                 0.0
                                                   10                0.0
                                                   11                0.0
                                 Craft-repair      9                 0.0
                                 Handlers-cleaners 7                 0.0
                                                   8                 0.0
                                                   10                0.0
                                 Machine-op-inspct 9                 0.0
                                 Other-service     5                 0.0
                                                   6                 0.0
                                                   7                 0.0
                                                   9                 0.0
                                                   10                0.0
                                 Priv-house-serv   6                 0.0
                                 Sales             6                 0.0
                                                   7                 0.0
                                                   8                 0.0
                                                   9                 0.0
                                                   10                0.0
              Other              ?                 6                 0.0
                                                   7                 0.0
                                                   8                 0.0
                                                   9                 0.0

In [31]:
agi_.loc[(60, 'Male', 'Black',)]

agi                                <=50K  >50K
occupation        education_years
?                 1                  1.0   0.0
                  2                  1.0   0.0
                  4                  1.0   0.0
                  5                  1.0   0.0
                  7                  1.0   0.0
                  8                  1.0   0.0
                  9                  1.0   0.0
                  10                 0.0   1.0
                  13                 1.0   0.0
                  14                 0.0   1.0
Adm-clerical      9                  1.0   0.0
                  13                 0.0   1.0
Craft-repair      4                  1.0   0.0
                  5                  1.0   0.0
                  6                  1.0   0.0
                  7                  0.0   1.0
                  9                  1.0   0.0
                  13                 1.0   0.0
Exec-managerial   5                  1.0   0.0
                  9                  0.5   0.5
                  10                 0.0   1.0
                  13                 0.0   1.0
                  15                 0.0   1.0
Farming-fishing   4                  1.0   0.0
                  5                  1.0   0.0
Handlers-cleaners 3                  1.0   0.0
                  6                  1.0   0.0
                  9                  1.0   0.0
Machine-op-inspct 5                  1.0   0.0
                  6                  1.0   0.0
                  9                  1.0   0.0
                  10                 0.0   1.0
Other-service     5                  1.0   0.0
                  6                  1.0   0.0
                  9                  1.0   0.0
                  10                 1.0   0.0
                  12                 1.0   0.0
Prof-specialty    7                  1.0   0.0
                  14                 1.0   0.0
                  16                 0.5   0.5
Protective-serv   5                  1.0   0.0
                  9                  1.0   0.0
Sales             9                  1.0   0.0
                  10                 0.0   1.0
                  13                 0.0   1.0
Transport-moving  4                  1.0   0.0
                  7                  1.0   0.0
                  9                  1.0   0.0
                  10                 1.0   0.0